name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUGSTER_CLI_API_KEY: ${{ secrets.BUGSTER_CLI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing Bugster CLI"
          curl -fsSL https://raw.githubusercontent.com/Bugsterapp/bugster-cli/giovaborgogno/DEV-33/scripts/install.sh | bash -s -- -v v0.2.9-beta.13 -y

      - name: Run tests
        run: |
          echo "Running tests"
          bugster test --headless
