name: Fake Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://fake.app.com
    steps:
      - name: Deploy
        run: echo "Deploying to Production"
